PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.FileUploadController Class Reference
com.theplanners.pkiclassroomrescheduler.system.FileUploadController Class Reference
Public Member Functions
FileUploadController (Schedule schedule, ClassroomList classroomList)
ArrayList< Section > uploadFile (@RequestParam("file") MultipartFile file)
Detailed Description
FileUpload controller hosts and endpoint at /api/upload that allows the upload of a csv file containing the current course assignment information. The uploaded csv then gets parsed and saved as a Schedule
See also
com.theplanners.pkiclassroomrescheduler.system.Schedule
Constructor & Destructor Documentation
FileUploadController()
com.theplanners.pkiclassroomrescheduler.system.FileUploadController.FileUploadController (Schedule schedule, ClassroomList classroomList)
Constructs a new FileUploadController with the provided Schedule and ClassroomList instances. Uses injection to share across components
Parameters
schedule The Schedule instance to use for managing course assignments.
classroomList The ClassroomList instance to use for managing classroom information.
Member Function Documentation
uploadFile()
ArrayList< Section > com.theplanners.pkiclassroomrescheduler.system.FileUploadController.uploadFile (@RequestParam("file") MultipartFile file)
Takes an uploaded csv file and reads each line, if it is a new section, which is determined by a blank first cell, then a new section instance is created and added to the schedule. Also reads classroom list at the time of upload.
Parameters
file csv file that is uploaded through the /api/upload endpoint
Returns
the schedule generated from the csv
See also
com.theplanners.pkiclassroomrescheduler.system.Schedule
com.theplanners.pkiclassroomrescheduler.system.Section
com.theplanners.pkiclassroomrescheduler.system.MeetingTimeConverter
References com.theplanners.pkiclassroomrescheduler.system.Schedule.addSection(), com.theplanners.pkiclassroomrescheduler.system.Schedule.clearSchedule(), com.theplanners.pkiclassroomrescheduler.system.MeetingTimeConverter.parseMeetingTime(), com.theplanners.pkiclassroomrescheduler.system.ReadClassroom.readClassroomCSV(), and com.theplanners.pkiclassroomrescheduler.system.Schedule.returnSchedule().
The documentation for this class was generated from the following file:
pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/FileUploadController.java