PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Schedule Class Reference
com.theplanners.pkiclassroomrescheduler.system.Schedule Class Reference
Public Member Functions
Schedule ()
void addSection (Section section)
ArrayList< Section > returnSchedule ()
void clearSchedule ()
Detailed Description
A Schedule is an object that contins all of the sections taking place in PKI.
Constructor & Destructor Documentation
Schedule()
com.theplanners.pkiclassroomrescheduler.system.Schedule.Schedule ()
Member Function Documentation
addSection()
void com.theplanners.pkiclassroomrescheduler.system.Schedule.addSection (Section section)
Adds a section to the ArrayList of sections.
Parameters
section The Section object to be added to the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.FileUploadController.uploadFile().
clearSchedule()
void com.theplanners.pkiclassroomrescheduler.system.Schedule.clearSchedule ()
Empties the list of sections in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.FileUploadController.uploadFile().
returnSchedule()
ArrayList< Section > com.theplanners.pkiclassroomrescheduler.system.Schedule.returnSchedule ()
Retrieves the entire schedule.
Returns
An ArrayList of every class in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.GetClassInfoController.getClassInfo(), com.theplanners.pkiclassroomrescheduler.system.GetClassInfoController.getMethodName(), com.theplanners.pkiclassroomrescheduler.system.AlgorithmController.runAlgorithm(), com.theplanners.pkiclassroomrescheduler.system.Algorithm.updateOverlaps(), and com.theplanners.pkiclassroomrescheduler.system.FileUploadController.uploadFile().
The documentation for this class was generated from the following file:
pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Schedule.java