PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm Class Reference
com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm Class Reference
Static Public Member Functions
static void updateOverlaps (Schedule schedule)
static ArrayList< Result > doAlgorithm (Section section, int newSize, Schedule schedule, ClassroomList classroomList)
Detailed Description
Algorithm is a class that takes a created schedule, which contains information for all courses, and performs analysis on each course to create relationships between them and determine which classrooms can support a given change to the schedule.
Member Function Documentation
doAlgorithm()
static ArrayList< Result > com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm (Section section, int newSize, Schedule schedule, ClassroomList classroomList) static
Our algorithm that analyzes the overlaps between each course in the schedule to determine the best option for rescheduling a given course.
Parameters
section The Section object within the schedule that needs to be rescheduled.
newSize An integer containign the updated course size that a classroom needs to accomodate.
schedule The Schedule object which is a collection of all sections in the schedule.
classroomList A ClassroomList object containing each Classroom object available in the building.
Returns
An array list containing Result objects that contain all
References com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm(), com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.getClassroomByNumber(), com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getOverlappingSections(), com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getRoomNumber(), com.theplanners.pkiclassroomrescheduler.system.Entities.Classroom.getSeats(), com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.returnClassrooms(), com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.updateOverlaps(), and com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.updateSchedule().
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm(), and com.theplanners.pkiclassroomrescheduler.system.Controllers.AlgorithmController.runAlgorithm().
updateOverlaps()
static void com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.updateOverlaps (Schedule schedule) static
Takes a schedule and adds overlaps to each section within the schedule if the two courses time's overlap.
Parameters
schedule The schedule object, which is a collection of all the currently scheduled courses.
References com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.returnSchedule().
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm().
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Utilites/Algorithm.java