PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule Class Reference
com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule Class Reference
Public Member Functions
Schedule ()
void addSection (Section section)
ArrayList< Section > returnSchedule ()
ArrayList< Section > returnCSSchedule ()
void clearSchedule ()
void updateCrosslist ()
void updateSchedule (Section sectionToUpdate, int newRoom)
Detailed Description
A Schedule is an object that contins all of the sections taking place in PKI.
Constructor & Destructor Documentation
Schedule()
com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.Schedule ()
Member Function Documentation
addSection()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.addSection (Section section)
Adds a section to the ArrayList of sections.
Parameters
section The Section object to be added to the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
clearSchedule()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.clearSchedule ()
Empties the list of sections in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
returnCSSchedule()
ArrayList< Section > com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.returnCSSchedule ()
Retrieves the computer science related courses from the schedule.
Returns
An ArrayList of every Computer Science course in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.ClearResultsController.clearResults(), and com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
returnSchedule()
ArrayList< Section > com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.returnSchedule ()
Retrieves the entire schedule.
Returns
An ArrayList of every class in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.AlgorithmController.runAlgorithm(), and com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.updateOverlaps().
updateCrosslist()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.updateCrosslist ()
Updates the crosslisting information in the schedule.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
updateSchedule()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Schedule.updateSchedule (Section sectionToUpdate, int newRoom)
Updates a section in the schedule with a new classroom assignment.
Parameters
sectionToUpdate The section that will be updated.
newRoom The new room number the section will be assigned to.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm().
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Entities/Schedule.java