PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Entities.Section Class Reference
com.theplanners.pkiclassroomrescheduler.system.Entities.Section Class Reference
Public Member Functions
Section (String course, int sectionNumber, String courseTitle, String sectionType, ArrayList< DayOfWeek > meetingDays, LocalTime startTime, LocalTime endTime, String instructor, int roomNumber, String instructionMethod, String crossList, int enrollment, int maxEnrollment)
void resetRoom ()
String getCourse ()
void setCourse (String course)
int getSectionNumber ()
void setSectionNumber (int sectionNumber)
String getCourseTitle ()
void setCourseTitle (String courseTitle)
String getSectionType ()
void setSectionType (String sectionType)
ArrayList< DayOfWeek > getMeetingDays ()
void setMeetingDays (ArrayList< DayOfWeek > meetingDays)
LocalTime getStartTime ()
void setStartTime (LocalTime startTime)
LocalTime getEndTime ()
void setEndTime (LocalTime endTime)
String getInstructor ()
void setInstructor (String instructor)
int getRoomNumber ()
void setRoomNumber (int roomNumber)
String getInstructionMethod ()
void setInstructionMethod (String instructionMethod)
String getCrossList ()
void setCrossList (String crossList)
int getEnrollment ()
void setEnrollment (int enrollment)
int getMaxEnrollment ()
void setMaxEnrollment (int maxEnrollment)
boolean Overlaps (Section otherSection)
ArrayList< Section > getOverlappingSections ()
void addOverlappingSection (Section section)
void setOverlappingSections (ArrayList< Section > overlappingSections)
void setCrossListMax (ArrayList< Section > schedule)
int getCrossListMax ()
void addCrossList (String crosslistedSection)
void setCrossListed (ArrayList< String > allCrossListed)
String toString ()
void clearOverlappingSections ()
Detailed Description
A Section is an object that contains all information about a class in the schedule. It is populated with information based on what is parsed from the uploaded csv.
Constructor & Destructor Documentation
Section()
com.theplanners.pkiclassroomrescheduler.system.Entities.Section.Section (String course, int sectionNumber, String courseTitle, String sectionType, ArrayList< DayOfWeek > meetingDays, LocalTime startTime, LocalTime endTime, String instructor, int roomNumber, String instructionMethod, String crossList, int enrollment, int maxEnrollment)
The constructor for a Section object, where each piece of relevant data can be added.
Parameters
course A string containing the course abbreviation and number Ex. CSCI 4800.
sectionNumber An integer containing the section number, for cases where there are multiple instances of the saem course.
courseTitle A string containing the actual title of a course Ex. Advanced Java Programming.
sectionType A string containing the type of course it is, such as a lab or lecture.
meetingDays A ArrayList containing each of the days of the week that the couse takes place on.
startTime A LocalTime object indicating the start time of the course.
endTime A LocalTime onject indicating the end time of the course.
instructor A string containing the name of the teacher for the course.
roomNumber An integer containing the room number in PKI that the class is currently taking place in.
instructionMethod A string indicating whether the course is taught in person, online, or hybrid.
crossList A String indicating any sections that the course is crosslisted with.
enrollment An integer indicating the current number of students enrolled in the course.
maxEnrollment An integer indicating the maximum number of students allowed in the course.
Member Function Documentation
addCrossList()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.addCrossList (String crosslistedSection)
Add a single course to the cross listed courses.
Parameters
crosslistedSection a section that is crosslisted with this section
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
addOverlappingSection()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.addOverlappingSection (Section section)
Adds an additional overlapping section to the section's list of overlapping sections.
Parameters
section The section to be added to the list of overlapping sections.
clearOverlappingSections()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.clearOverlappingSections ()
Clears the overlapping sections.
getCourse()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCourse ()
Retrives the course abbreviation from the Section.
Returns
A string containing the course abbreviation.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Entities.Result.Result().
getCourseTitle()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCourseTitle ()
Retrieves the course's title.
Returns
A string containing the course's title.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Entities.Result.Result().
getCrossList()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCrossList ()
Retrieves the name of the courses crosslisted with the course.
Returns
A string containing the names of crosslisted courses.
getCrossListMax()
int com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCrossListMax ()
Return the max course size considering cross listings
Returns
max course size including crosslisted courses.
getEndTime()
LocalTime com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getEndTime ()
Retrieves the ending time of the course.
Returns
A LocalTime object containing the course's ending time.
getEnrollment()
int com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getEnrollment ()
Retrieves the enrollment number of the course.
Returns
An integer containing the number of students enrolled in the course.
getInstructionMethod()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getInstructionMethod ()
Retrieves the intruction method of the course.
Returns
A string containing the course's new instruction method.
getInstructor()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getInstructor ()
Retrieves the teacher of the course.
Returns
A string containting the course's instructor.
getMaxEnrollment()
int com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getMaxEnrollment ()
Retrieves the maximum enrollment of the course.
Returns
An integer containing the maximum enrollment of the course.
getMeetingDays()
ArrayList< DayOfWeek > com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getMeetingDays ()
Retrieves the meeting days of the course.
Returns
An ArrayList of the days of the week the course meets.
getOverlappingSections()
ArrayList< Section > com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getOverlappingSections ()
Retrieves the sections that the course overlaps with.
Returns
An ArrayList containing Section objects that the section overlaps with.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm().
getRoomNumber()
int com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getRoomNumber ()
Retrieves the room number of the course.
Returns
An integer containing the room number of course's classroom in PKI.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm().
getSectionNumber()
int com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getSectionNumber ()
Retrieves the course's section number.
Returns
An integer containing the course's section number.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Entities.Result.Result().
getSectionType()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getSectionType ()
Retrieves the course's section type.
Returns
A string containing the course's section type.
getStartTime()
LocalTime com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getStartTime ()
Retrieves the start time of the course.
Returns
A LocalTime object containing the course's starting time.
Overlaps()
boolean com.theplanners.pkiclassroomrescheduler.system.Entities.Section.Overlaps (Section otherSection)
Indicates if the current section overlaps in time with another given section.
Parameters
otherSection The Section to be compared to this section.
Returns
A boolean indicating if the two courses overlap.
resetRoom()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.resetRoom ()
Sets the section's assigned room back to its original value.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.ClearResultsController.clearResults().
setCourse()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setCourse (String course)
Sets the course abbreviation for the Section.
Parameters
course A string containing the new course abbreviation.
setCourseTitle()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setCourseTitle (String courseTitle)
Sets the course's title.
Parameters
courseTitle A string containing the course's new title.
setCrossList()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setCrossList (String crossList)
Sets the cross listed courses associated with the course.
Parameters
crossList A String containing the new courses that are crosslisted.
setCrossListed()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setCrossListed (ArrayList< String > allCrossListed)
Set the entire crosslisted sections
Parameters
allCrossListed an arraylist of all crosslisted sections
setCrossListMax()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setCrossListMax (ArrayList< Section > schedule)
setEndTime()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setEndTime (LocalTime endTime)
Sets the course's ending time.
Parameters
startTime A LocalTime object containing the course's new ending time
setEnrollment()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setEnrollment (int enrollment)
Sets the enrollment number of the course.
Parameters
enrollment An integer containing the new number of student enrolled in the course.
setInstructionMethod()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setInstructionMethod (String instructionMethod)
Sets the instruction method of the course.
Parameters
instructionMethod A string containing the course's new instruction method.
setInstructor()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setInstructor (String instructor)
Sets the course's instructor.
Parameters
instructor A string containing the course's new instructor.
setMaxEnrollment()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setMaxEnrollment (int maxEnrollment)
Sets the maximum enrollment number of the course.
Parameters
maxEnrollment An integer containing the new maximum enrollment number.
setMeetingDays()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setMeetingDays (ArrayList< DayOfWeek > meetingDays)
Sets the course's meeting days.
Parameters
meetingDays An ArrayList containing the new days of the week the course meets.
setOverlappingSections()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setOverlappingSections (ArrayList< Section > overlappingSections)
Set the section's overlapping sections.
Parameters
overlappingSections An ArrayList containing the section's new overlapping sections.
setRoomNumber()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setRoomNumber (int roomNumber)
Sets the room number of the course.
Parameters
roomNumber An integer containing the new room number of the course's classroom in PKI.
setSectionNumber()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setSectionNumber (int sectionNumber)
Sets the course's section number.
Parameters
sectionNumber An integer containing the new section number.
setSectionType()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setSectionType (String sectionType)
Sets the course's section type.
Parameters
sectionType A string containing the course's new section type.
setStartTime()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Section.setStartTime (LocalTime startTime)
Sets the course's start time.
Parameters
startTime A LocalTime object containing the course's new start time
toString()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Section.toString ()
Formats the section's information into a readable string.
Returns
A string containing all the section's information.
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Entities/Section.java