PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Algorithm Class Reference
com.theplanners.pkiclassroomrescheduler.system.Algorithm Class Reference
Public Member Functions
String doAlgorithmOld (Section section, int newSize, Schedule schedule, ClassroomList classroomList)
Static Public Member Functions
static void updateOverlaps (Schedule schedule)
static String doAlgorithm (Section section, int newSize, Schedule schedule, ClassroomList classroomList)
Detailed Description
Algorithm is a class that takes a created schedule, which contains information for all courses, and performs analysis on each course to create relationships between them and determine which classrooms can support a given change to the schedule.
Member Function Documentation
doAlgorithm()
static String com.theplanners.pkiclassroomrescheduler.system.Algorithm.doAlgorithm (Section section, int newSize, Schedule schedule, ClassroomList classroomList) static
Our algorithm that analyzes the overlaps between each course in the schedule to determine the best option for rescheduling a given course.
Parameters
section The Section object within the schedule that needs to be rescheduled.
newSize An integer containign the updated course size that a classroom needs to accomodate.
schedule The Schedule object which is a collection of all sections in the schedule.
classroomList A ClassroomList object containing each Classroom object available in the building.
Returns
A string containing the best choice for a different classroom, options equal to the best, and options worse than the best.
References com.theplanners.pkiclassroomrescheduler.system.Classroom.getRoom(), com.theplanners.pkiclassroomrescheduler.system.ClassroomList.returnClassrooms(), and com.theplanners.pkiclassroomrescheduler.system.Algorithm.updateOverlaps().
Referenced by com.theplanners.pkiclassroomrescheduler.system.AlgorithmController.runAlgorithm().
doAlgorithmOld()
String com.theplanners.pkiclassroomrescheduler.system.Algorithm.doAlgorithmOld (Section section, int newSize, Schedule schedule, ClassroomList classroomList)
An older version of our Algorithm that simply checks if each classroom can fit the given class and outputs all classrooms that can. Only used for testing and will later be removed.
Parameters
section The Section object within the schedule that needs to be rescheduled.
newSize An integer containing the updated size of the class that a classroom needs to accomodate.
schedule The Schedule object which is a collection of all sections in the schedule.
classroomList A ClassroomList object containing each Classroom object available in the building.
Returns
A string containing all of the classrooms that the given section can fit in.
References com.theplanners.pkiclassroomrescheduler.system.Section.getRoomNumber(), com.theplanners.pkiclassroomrescheduler.system.ClassroomList.returnClassrooms(), and com.theplanners.pkiclassroomrescheduler.system.Algorithm.updateOverlaps().
updateOverlaps()
static void com.theplanners.pkiclassroomrescheduler.system.Algorithm.updateOverlaps (Schedule schedule) static
Takes a schedule and adds overlaps to each section within the schedule if the two courses time's overlap.
Parameters
schedule The schedule object, which is a collection of all the currently scheduled courses.
References com.theplanners.pkiclassroomrescheduler.system.Schedule.returnSchedule().
Referenced by com.theplanners.pkiclassroomrescheduler.system.Algorithm.doAlgorithm(), and com.theplanners.pkiclassroomrescheduler.system.Algorithm.doAlgorithmOld().
The documentation for this class was generated from the following file:
pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Algorithm.java