PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Entities.Result Class Reference
com.theplanners.pkiclassroomrescheduler.system.Entities.Result Class Reference
Public Member Functions
Result (Section section, Classroom oldClassroom, Classroom newClassroom, ArrayList< Classroom > otherEqualClassrooms, ArrayList< Classroom > otherWorseClassrooms, int newSize)
Section getSection ()
void setNewClassroom (Classroom newClassroom)
String toString ()
Detailed Description
The Result object stores all relevant information about the result of the algorithm for easy access.
Constructor & Destructor Documentation
Result()
com.theplanners.pkiclassroomrescheduler.system.Entities.Result.Result (Section section, Classroom oldClassroom, Classroom newClassroom, ArrayList< Classroom > otherEqualClassrooms, ArrayList< Classroom > otherWorseClassrooms, int newSize)
The constructor for a Result object
Parameters
section The section of the course that was rescheduled.
oldClassroom The section's classroom assignment before the algorithm executed.
newClassroom The section's new classroom assignment after the algorithm executed.
otherEqualClassrooms Other available classrooms of equal efficiency to the newClassroom.
otherWorseClassrooms Other available classrooms of worse efficiency than the newClassroom.
newSize The new size that the section can accomodate.
References com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCourse(), com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getCourseTitle(), and com.theplanners.pkiclassroomrescheduler.system.Entities.Section.getSectionNumber().
Member Function Documentation
getSection()
Section com.theplanners.pkiclassroomrescheduler.system.Entities.Result.getSection ()
setNewClassroom()
void com.theplanners.pkiclassroomrescheduler.system.Entities.Result.setNewClassroom (Classroom newClassroom)
toString()
String com.theplanners.pkiclassroomrescheduler.system.Entities.Result.toString ()
Formats the result's information into a readable string.
Returns
A string containing all of the result's information.
References com.theplanners.pkiclassroomrescheduler.system.Entities.Classroom.getRoom().
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.AlgorithmController.runAlgorithm().
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Entities/Result.java