PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList Class Reference
com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList Class Reference
Public Member Functions
ClassroomList ()
void addClassroom (Classroom classroom)
ArrayList< Classroom > returnClassrooms ()
void setClassrooms (ArrayList< Classroom > newClassrooms)
void clearClassrooms ()
Classroom getClassroomByNumber (int roomNumber)
Detailed Description
ClassroomList is a class that serves as an object representing a list of classrooms along with all of the actions that are able to be taken to with the list of classrooms.
Constructor & Destructor Documentation
ClassroomList()
com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.ClassroomList ()
The constructor for the ClassroomList class. The constructor stores a list of classroom objects into an ArrayList.
Member Function Documentation
addClassroom()
void com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.addClassroom (Classroom classroom)
Adds a classroom to the ArrayList of classrooms that is intitialized within the class constructor.
Parameters
classroom the classroom to be added to the classroom list
clearClassrooms()
void com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.clearClassrooms ()
Empties the list of classrooms.
getClassroomByNumber()
Classroom com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.getClassroomByNumber (int roomNumber)
Finds a classroom based on the room number.
Parameters
roomNumber An integer of the room number to be found.
Returns
A classroom object that matches the number input.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm().
returnClassrooms()
ArrayList< Classroom > com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.returnClassrooms ()
Returns the ArrayList containing lassroom objects.
Returns
the ArrayList of classrooms to be returned.
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.Algorithm.doAlgorithm(), and com.theplanners.pkiclassroomrescheduler.system.Controllers.ClassroomInfoController.returnClassroomList().
setClassrooms()
void com.theplanners.pkiclassroomrescheduler.system.Entities.ClassroomList.setClassrooms (ArrayList< Classroom > newClassrooms)
Sets the list of classrooms provided an input ArrayList of classrooms.
Parameters
newClassrooms the ArrayList of new classrooms
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.ReadClassroom.readClassroomCSV().
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Entities/ClassroomList.java