PKI Classroom Rescheduler: com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter Class Reference
com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter Class Reference
Classes
class MeetingTime
Static Public Member Functions
static MeetingTime parseMeetingTime (String meetingTimeString)
static ArrayList< DayOfWeek > convertToDayOfWeek (String daysString)
static LocalTime convertToLocalTime (String timeString)
Detailed Description
MeetingTimeConverter is a class that converts the meeting time string (Ex: "MW 3pm-4:15pm") into easier to use formats, an ArrayList<DayOfWeek> for meeting days and a LocalTime for each the start and end time.
Member Function Documentation
convertToDayOfWeek()
static ArrayList< DayOfWeek > com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.convertToDayOfWeek (String daysString) static
Given a string, formatted "MW" or "F" representing Monday, Wednesday and Friday respectively, return an ArrayList of DayOfWeek enumerations Ex: "MW" -> [MONDAY, WEDNESDAY]
Parameters
daysString the string containing the meeting days
Returns
ArrayList of DayOfWeek enumerations representing the input string
See also
java.time.DayOfWeek
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.parseMeetingTime().
convertToLocalTime()
static LocalTime com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.convertToLocalTime (String timeString) static
Takes a time in the format "3pm" or "8am" and converts it to java.LocalTime
Parameters
timeString the string containing the a time in format "3pm"
Returns
the time represented as a LocalTime
See also
java.LocalTime
Referenced by com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.parseMeetingTime().
parseMeetingTime()
static MeetingTime com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.parseMeetingTime (String meetingTimeString) static
Takes a meeting time string, formatted as "MW 3pm-4:15pm", parses out the meeting days and meeting times, and returns tham as a MeetingTime object.
Parameters
meetingTimeString String directly from csv in format "MW 3pm-4:15pm"
Returns
MeetingTime: a custom class that contains the meeting days, the start time, and the end time. or returns null if pattern doesn't match.
References com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.convertToDayOfWeek(), and com.theplanners.pkiclassroomrescheduler.system.Utilites.MeetingTimeConverter.convertToLocalTime().
Referenced by com.theplanners.pkiclassroomrescheduler.system.Controllers.FileUploadController.uploadFile().
The documentation for this class was generated from the following file:
C:/Users/ksril/Desktop/Vscode/ThePlanners-PKI-Room-Scheduler/pkiclassroomrescheduler/src/main/java/com/theplanners/pkiclassroomrescheduler/system/Utilites/MeetingTimeConverter.java